project:
  type: website

website:
  title: "CSDC Yield Loss"
  navbar:
    left:
      - href: index.qmd 
        text: Home 
      - href: new_code2.qmd 
        text: Code 
      - href: mapa2.qmd 
        text: Map
    right:
      - icon: github
        href: https://github.com/marcelo625
      - icon: linkedin
        href: https://www.linkedin.com/in/marcelohogon%C3%A7alves/
      - icon: twitter
        href: https://x.com/marcelo_hog
      - icon: instagram
        href: https://www.instagram.com/marcelo.625
      
format:
  html:
    theme:
      - flatly
      - flatly
    css: styles.css
    toc: true

editor: visual

